[package]
name = "vmp_analyzer"
version = "0.0.1"
edition = "2021"



[dependencies]
crossterm = { version = "0.26.1", features = [ "serde" ] }
tui = "0.19.0"
goblin = "0.6.1"
zydis = "3.1.3"
unicorn-engine = "2.0.1"
